### ISSUE TITLE
Upgrade?

### ISSUE THREAD

**Issue by Moscarda** [fvcproductions/dotfiles#1]
Hello, this looks great.  Sorry if this is not the place to ask, but I am new to development.  

If I already have some of these tools installed, will these scripts just reconfigure them?  

I'm worried I may have misconfigured some Homebrew and NPM installs, and some directories may be out of place due to problems with my $PATH / bash profile.

Cheers

**Comment by fvcproductions** [comment]
No problem, issues are a great place to ask questions! 😄

Yes, the script will override your preferences and settings since it is intended for fresh installs on new computers. 

If you want to use the settings within the repo, I would clone it and then edit it your heart's desire so it fits your `$PATH` and doesn't reconfigure it a different way than intended.

Hope this helps and apologies for late reply!
